# Screen dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Game settings
GAME_FPS = 60

# Player settings
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3  # seconds
PLAYER_TRIANGLE_SCALE = 1.5  # Used for triangle shape calculation

# Shot settings
SHOT_RADIUS = 5
SHOT_LINE_WIDTH = 2

# Asteroid settings
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_SPEED = 40
ASTEROID_MAX_SPEED = 100
ASTEROID_ROTATION_VARIANCE = 30  # degrees
ASTEROID_SPLIT_ANGLE_MIN = 20
ASTEROID_SPLIT_ANGLE_MAX = 50
ASTEROID_SPLIT_SPEED_MULTIPLIER = 1.2

# Scoring
SCORE_SMALL_ASTEROID = 100
SCORE_MEDIUM_ASTEROID = 50
SCORE_LARGE_ASTEROID = 20

# UI settings
UI_SCORE_FONT_SIZE = 36
UI_GAME_OVER_TITLE_SIZE = 72
UI_GAME_OVER_TEXT_SIZE = 48
UI_GAME_OVER_INSTRUCTION_SIZE = 36
UI_SCORE_X_POSITION = 20
UI_SCORE_Y_POSITION = 30
UI_HIGH_SCORE_Y_POSITION = 70
UI_GAME_OVER_Y_OFFSET = 100
UI_GAME_OVER_SCORE_Y_OFFSET = 40
UI_GAME_OVER_INSTRUCTION_Y_OFFSET = 50

# Drawing settings
DEFAULT_LINE_WIDTH = 2
